import { useEffect, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useLocation } from 'wouter';
import { Bell, Check, ChevronRight, FolderPlus, KeyRound, Lock, Mail, Plus, Shield, UserRound } from 'lucide-react';
import { getGetCurrentUserQueryKey, getListFoldersQueryKey, getListNotificationsQueryKey, getListSubscriptionsQueryKey, useCreateFolder, useCreateSubscription, useGetCurrentUser, useListFolders, useListNotifications, useListSubscriptions, useMarkNotificationRead, useUpdateProfile } from '@workspace/api-client-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Switch } from '@/components/ui/switch';
import { MailShell } from '@/components/mail-shell';

const fmt = (date: string) => new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(date));

export default function SettingsPage() {
  const [location] = useLocation();
  const client = useQueryClient();
  const user = useGetCurrentUser();
  const folders = useListFolders();
  const subs = useListSubscriptions();
  const notifications = useListNotifications();
  const updateProfile = useUpdateProfile();
  const createFolder = useCreateFolder();
  const createSubscription = useCreateSubscription();
  const markNotification = useMarkNotificationRead();
  const [username, setUsername] = useState('');
  const [folderName, setFolderName] = useState('');
  const [subEmail, setSubEmail] = useState('');
  const [subLabel, setSubLabel] = useState('');
  const [notice, setNotice] = useState('');
  const requestedPanel = new URLSearchParams(location.split('?')[1] ?? '').get('panel') || 'account';
  const [open, setOpen] = useState(requestedPanel);
  useEffect(() => { if (requestedPanel) setOpen(requestedPanel); }, [requestedPanel]);
  const [privacy, setPrivacy] = useState({ read: true, blocked: true, alerts: true });
  const show = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 3200); };
  const saveName = () => { if (username.trim()) updateProfile.mutate({ data: { username: username.trim() } }, { onSuccess: () => { client.invalidateQueries({ queryKey: getGetCurrentUserQueryKey() }); show('Profile updated.'); } }); };
  const addFolder = () => { if (folderName.trim()) createFolder.mutate({ data: { name: folderName.trim() } }, { onSuccess: () => { setFolderName(''); client.invalidateQueries({ queryKey: getListFoldersQueryKey() }); show('Folder created.'); } }); };
  const addSub = () => { if (subEmail.includes('@') && subLabel.trim()) createSubscription.mutate({ data: { email: subEmail.trim(), label: subLabel.trim() } }, { onSuccess: () => { setSubEmail(''); setSubLabel(''); client.invalidateQueries({ queryKey: getListSubscriptionsQueryKey() }); show('Subscription added.'); } }); };
  return <MailShell><div className="mx-auto max-w-[1000px] p-5 sm:p-8"><div className="mb-9"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-primary">Control room</p><h1 className="mt-2 font-display text-5xl tracking-[-.04em]">Settings<span className="text-primary">.</span></h1><p className="mt-3 text-sm text-muted-foreground">A few thoughtful choices about your address and your attention.</p></div>{notice && <div className="fixed right-5 top-20 z-50 flex items-center gap-2 rounded-xl border border-primary/30 bg-[#18100f] px-4 py-3 text-sm text-primary shadow-2xl animate-enter" data-testid="status-settings-success"><Check className="h-4 w-4" />{notice}</div>}
    <div className="space-y-3">
      <section className="glass overflow-hidden rounded-2xl"><button onClick={() => setOpen(open === 'account' ? '' : 'account')} className="flex w-full items-center justify-between p-5 text-left sm:p-6" data-testid="button-toggle-account"><span className="flex items-center gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><UserRound className="h-5 w-5" /></span><span><span className="block font-semibold">Account identity</span><span className="mt-1 block text-xs text-muted-foreground">Your name, address, and access key status</span></span></span><ChevronRight className={`h-4 w-4 text-muted-foreground transition-transform ${open === 'account' ? 'rotate-90' : ''}`} /></button>{open === 'account' && <div className="border-t hairline px-5 pb-6 pt-5 sm:px-6"><div className="grid gap-6 md:grid-cols-2"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground">Display name</p><div className="mt-3 flex gap-2"><Input defaultValue={user.data?.username} onChange={e => setUsername(e.target.value)} placeholder={user.data?.username ?? 'Your name'} className="bg-white/[.04]" data-testid="input-profile-name" /><Button onClick={saveName} disabled={updateProfile.isPending} data-testid="button-save-profile">{updateProfile.isPending ? 'Saving…' : 'Save'}</Button></div></div><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground">Mailbox address</p><p className="mt-3 text-sm">{user.data?.email ?? '—'}</p><p className="mt-1 text-xs text-muted-foreground">Address changes remaining: <span className="text-primary">{user.data?.emailChangesRemaining ?? 0}</span></p></div></div><div className="mt-7 flex items-center gap-3 rounded-xl border border-primary/20 bg-primary/5 p-4 text-xs leading-5 text-muted-foreground"><KeyRound className="h-4 w-4 shrink-0 text-primary" />Your access key is the only credential. FPEDS cannot reset it, and never stores it in readable form.</div></div>}</section>
       <section className="glass overflow-hidden rounded-2xl"><button onClick={() => setOpen(open === 'privacy' ? '' : 'privacy')} className="flex w-full items-center justify-between p-5 text-left sm:p-6" data-testid="button-toggle-privacy"><span className="flex items-center gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Shield className="h-5 w-5" /></span><span><span className="block font-semibold">Privacy & security</span><span className="mt-1 block text-xs text-muted-foreground">Keep the room private and notifications intentional</span></span></span><ChevronRight className={`h-4 w-4 text-muted-foreground transition-transform ${open === 'privacy' ? 'rotate-90' : ''}`} /></button>{open === 'privacy' && <div className="border-t hairline px-5 pb-6 pt-2 sm:px-6">{[['read', 'Read receipts', 'Show senders when you open their message.'], ['blocked', 'Block suspicious mail', 'Keep high spam-score messages out of your inbox.'], ['alerts', 'Quiet notifications', 'Only notify for messages that need a response.']].map(([key, title, desc]) => <div key={key} className="flex items-center justify-between border-b border-white/[.07] py-4 last:border-0"><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-muted-foreground">{desc}</p></div><Switch checked={privacy[key as keyof typeof privacy]} onCheckedChange={checked => setPrivacy({ ...privacy, [key]: checked })} data-testid={`switch-${key}`} /></div>)}</div>}</section>
      <section className="glass overflow-hidden rounded-2xl"><button onClick={() => setOpen(open === 'subscriptions' ? '' : 'subscriptions')} className="flex w-full items-center justify-between p-5 text-left sm:p-6" data-testid="button-toggle-subscriptions"><span className="flex items-center gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Mail className="h-5 w-5" /></span><span><span className="block font-semibold">Subscriptions</span><span className="mt-1 block text-xs text-muted-foreground">Mailboxes and addresses that may deliver to you</span></span></span><ChevronRight className={`h-4 w-4 text-muted-foreground transition-transform ${open === 'subscriptions' ? 'rotate-90' : ''}`} /></button>{open === 'subscriptions' && <div className="border-t hairline px-5 pb-6 pt-5 sm:px-6"><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><Input value={subEmail} onChange={e => setSubEmail(e.target.value)} placeholder="sender@domain.com" data-testid="input-subscription-email" /><Input value={subLabel} onChange={e => setSubLabel(e.target.value)} placeholder="Label, e.g. essays" data-testid="input-subscription-label" /><Button onClick={addSub} disabled={createSubscription.isPending} data-testid="button-add-subscription"><Plus className="h-4 w-4" /> Add</Button></div><div className="mt-5 space-y-2">{(subs.data ?? []).length === 0 ? <p className="py-5 text-center text-xs text-muted-foreground">No subscriptions yet.</p> : (subs.data ?? []).map(sub => <div key={sub.id} className="flex items-center justify-between rounded-xl bg-white/[.035] px-4 py-3"><div><p className="text-sm">{sub.label}</p><p className="font-mono text-[10px] text-muted-foreground">{sub.email}</p></div><span className={`font-mono text-[9px] uppercase tracking-[.14em] ${sub.active ? 'text-primary' : 'text-muted-foreground'}`}>{sub.active ? 'Active' : 'Paused'}</span></div>)}</div></div>}</section>
      <section className="glass overflow-hidden rounded-2xl"><button onClick={() => setOpen(open === 'folders' ? '' : 'folders')} className="flex w-full items-center justify-between p-5 text-left sm:p-6" data-testid="button-toggle-folders"><span className="flex items-center gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><FolderPlus className="h-5 w-5" /></span><span><span className="block font-semibold">Mailbox folders</span><span className="mt-1 block text-xs text-muted-foreground">Give your messages a place to land</span></span></span><ChevronRight className={`h-4 w-4 text-muted-foreground transition-transform ${open === 'folders' ? 'rotate-90' : ''}`} /></button>{open === 'folders' && <div className="border-t hairline px-5 pb-6 pt-5 sm:px-6"><div className="flex gap-2"><Input value={folderName} onChange={e => setFolderName(e.target.value)} maxLength={40} placeholder="New folder name" data-testid="input-folder-name" /><Button onClick={addFolder} disabled={createFolder.isPending} data-testid="button-create-folder"><Plus className="h-4 w-4" /> Create</Button></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{(folders.data ?? []).map(folder => <div key={folder.id} className="flex items-center justify-between rounded-lg border border-white/[.07] px-4 py-3 text-sm"><span>{folder.name}</span><span className="font-mono text-[10px] text-muted-foreground">{folder.count}</span></div>)}</div></div>}</section>
      <section className="glass overflow-hidden rounded-2xl"><button onClick={() => setOpen(open === 'notifications' ? '' : 'notifications')} className="flex w-full items-center justify-between p-5 text-left sm:p-6" data-testid="button-toggle-notifications"><span className="flex items-center gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Bell className="h-5 w-5" /></span><span><span className="block font-semibold">Notifications</span><span className="mt-1 block text-xs text-muted-foreground">Recent activity from your private workspace</span></span></span><ChevronRight className={`h-4 w-4 text-muted-foreground transition-transform ${open === 'notifications' ? 'rotate-90' : ''}`} /></button>{open === 'notifications' && <div className="border-t hairline px-5 pb-6 pt-5 sm:px-6">{(notifications.data ?? []).length === 0 ? <p className="py-6 text-center text-xs text-muted-foreground">No new notifications.</p> : (notifications.data ?? []).map(note => <button key={note.id} onClick={() => markNotification.mutate({ id: note.id }, { onSuccess: () => client.invalidateQueries({ queryKey: getListNotificationsQueryKey() }) })} className="flex w-full gap-3 border-b border-white/[.07] py-4 text-left last:border-0" data-testid={`button-notification-${note.id}`}><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${note.isRead ? 'bg-muted' : 'bg-primary'}`} /><span className="min-w-0"><p className="text-sm font-medium">{note.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{note.message}</p><p className="mt-2 font-mono text-[9px] uppercase tracking-[.12em] text-muted-foreground">{fmt(note.createdAt)} · {note.isRead ? 'Read' : 'Mark read'}</p></span></button>)}</div>}</section>
    </div>
    <div className="mt-7 flex items-center gap-2 text-xs text-muted-foreground"><Lock className="h-3.5 w-3.5 text-primary" /> Private workspace · created {user.data?.createdAt ? fmt(user.data.createdAt) : '—'}</div>
  </div></MailShell>;
}